ls:
	bash ls.sh

create_files:
	touch 流星雨.txt cal.exe demo.txt netmonitor.exe
	chmod 444 流星雨.txt
	chmod 111 cal.exe
	chmod 766 demo.txt
	chmod u+s netmonitor.exe

clean:
	rm 流星雨.txt cal.exe demo.txt netmonitor.exe -f